### ISSUE TITLE
[Task][Client]-  메인 화면 랜덤 테마 기능 만들기(유저 피드백)

### ISSUE THREAD

**Issue by ByungyeonKim** [devdynam0507/picker#37]
> ### ISSUE
> * Group:  `client`
> * Type: `feature`
> * Detail: 해당 웹 앱을 사용해보신 동기분께서 "테마도 랜덤으로 골라주면 좋을 것 같아요."라고 하셨습니다. 메인 화면의 메뉴 Picker를 랜덤 Picker 기능으로 만들어보겠습니다.
> 
> ### TODO
> 1. [x]  '메뉴 Picker' 섹션을 랜덤으로 테마를 골라주는 '랜덤 Picker' 버튼으로 만들기
> 2. [x]  랜덤 Picker 버튼 클릭 시 테마를 랜덤으로 골라주는 기능 구현하기
>

**Comment by developerjhp** [comment]
너무 좋은 생각인 것 같아요~!!!

**Comment by ByungyeonKim** [comment]
@developerjhp 휴파가 기능구현을 해줬습니다 감사합니다! 👍
