### ISSUE TITLE
[Task][Client]-  메인으로 돌아가는 버튼 만들기

### ISSUE THREAD

**Issue by tamagoyakii** [devdynam0507/picker#45]
> ### ISSUE
> * Group:  `client`
> * Type: `feature`
> * Detail: 메인이 아닌 페이지에서 메인으로 돌아갈 수 있는 버튼을 만들면 좋을 것 같습니다. (카카오맵으로 길찾기 아래)
> 
> ### TODO
> 1. [x]  지도보이는 화면에서 메인으로 가는 버튼 만들기

**Comment by developerjhp** [comment]
확인했습니다!

**Comment by ByungyeonKim** [comment]
피드백 감사합니다..! 빠르게 적용 해볼게요~ 😃

**Comment by developerjhp** [comment]
#53  적용했습니다!
