### ISSUE TITLE
[Feedback]주니어 프론트엔드 개발자의 피드백입니다.

### ISSUE THREAD

**Issue by pearpearB** [devdynam0507/picker#56]
- [x] 처음 picker를 선택했을 때, 위의 음식 아이콘들과 아래 버튼의 css가 너무 똑같아요!
- [x] 마찬가지로 picker를 선택하고 가게지도페이지가 나올 때, 가게 이름과 아래 버튼들의 css가 같아 무엇이 버튼인 지 혼동될 것 같아요! 다르게 해 주었으면 좋겠습니다:)

**Comment by ByungyeonKim** [comment]
디자인 수정을 완료하여 해당 이슈는 Close 하겠습니다.
