### ISSUE TITLE
[Task][Client]- UI 디자인 개선, Tailwind CSS 추가

### ISSUE THREAD

**Issue by ByungyeonKim** [devdynam0507/picker#57]
> ### ISSUE
> * Group:  `client`
> * Type: `feature`
> * Detail: Picker 디자인 대폭 개선, Tailwind CSS 적용
> 
> ### TODO
> 1. [ ]  Picker UI 디자인 대폭 개선하기

|디자인 개선 전|디자인 개선 후|
|------|---|
|![제목을-입력해주세요_-001](https://user-images.githubusercontent.com/66554164/154839636-30a7f59d-0bf9-4e96-99bc-5c74d0a50e17.png)|<img width="1503" alt="스크린샷 2022-02-20 오후 8 06 03" src="https://user-images.githubusercontent.com/66554164/154839650-56513c32-f321-4968-8c10-552347cb4515.png">|
> 
> 2. [x]  Tailwind CSS framework 추가하기

**Comment by devdynam0507** [comment]
와 정말 이뻐졌네요

**Comment by ByungyeonKim** [comment]
@devdynam0507 감사합니다 ㅎㅎ 아직 적용은 안됐지만 시간 나는대로 작업 중이에요..! :)
