### ISSUE TITLE
[Bug] Win64, Chrome 환경에서 음식 아이콘이 ㅁ로 표시되는 이슈

### ISSUE THREAD

**Issue by devdynam0507** [devdynam0507/picker#62]
**Describe the bug**
_picker 메인 페이지 음식 아이콘이 ㅁ으로 표시됩니다._

**To Reproduce**
1. 피커 접속

**Expected behavior**
원래는 아이콘이 저기에 뜨는게 맞는것같은데 현재로썬 깨져서 나옵니다.

**Screenshots**
![pickEr-bug](https://user-images.githubusercontent.com/23313008/160042762-c97c2285-4ff4-49c4-92ea-8e3f134d5e63.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Browser Chrome
 - Version Chrome 99.0.4844.82

**Comment by ByungyeonKim** [comment]
Mac 이모티콘을 사용했더니 윈도우에선 저렇게 보이는군요..! 윈도우 환경을 고려 못했네요! 대체할 이미지를 찾아봐야겠어요. 감사합니다! 👏

**Comment by younhoso** [comment]
아이콘이 텍스트로 인지해서 발생하는것 같은데 보통 저같은 경우에는 아이콘을 css로 만들어서 사용합니다.
https://triplexlab.tistory.com/52 제가 정리해놓은 글인데 참고 하세요~

**Comment by younhoso** [comment]
> 그러나 이마저도 Mac을 사용하지 않아도 됩니다..! 안전하다고 생각합니다! 그것을 보고 싶어요. 감사합니다!👏

아이콘이 같은 문자로 인해 빨라졌습니다.
https://triplexlab.tistory.com/52 '멋지다' 생각하세요~

**Comment by ByungyeonKim** [comment]
@younhoso 오..감사합니다! 보내주신 글 잘 읽었습니다. 
해당 이슈는 저희 디자인을 예쁘게 바꿔주신 디자이너분께 피드백 드린 상태입니다. 적당한 이미지를 찾아서 SVG 형태로 주신다고 하네요. 😄
이미지를 받고 나서 사용해봐야겠어요! 🤩

**Comment by ByungyeonKim** [comment]
해당 이슈는 이미지 파일로 대체하여 Close 하겠습니다!
